add SymCrypt-debuginfo package

diff --git a/SPECS/SymCrypt/find-debuginfo b/SPECS/SymCrypt/find-debuginfo
--- a/SPECS/SymCrypt/find-debuginfo
+++ b/SPECS/SymCrypt/find-debuginfo
@@ -28,6 +28,7 @@ automagically generates debug info and file lists
 Options:
 [--strict-build-id] [-g] [-r] [-m] [-i] [-n]
 [--keep-section SECTION] [--remove-section SECTION]
+[--keep-symbol SYMBOL]
 [--g-libs]
 [-j N] [--jobs N]
 [-o debugfiles.list]
@@ -51,6 +52,9 @@ Use --keep-section SECTION or --remove-section SECTION to explicitly
 keep a (non-allocated) section in the main executable or explicitly
 remove it into the .debug file. SECTION is an extended wildcard
 pattern.  Both options can be given more than once.
+
+Use --keep-symbol SYMBOL to keep the symbol in the main executable.
+This option can be given more than once.
 
 The --strict-build-id flag says to exit with failure status if
 any ELF binary processed fails to contain a build-id note.
@@ -99,7 +103,9 @@ EOF
 }
 
 # Figure out where we are installed so we can call other helper scripts.
-install_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+# SymCrypt-Specific: Because we have our own custom find-debuginfo, we need to use the
+# location that the system version is installed at.
+install_dir="$(cd "$(dirname "$(which find-debuginfo)")" && pwd)"
 
 # With -g arg, pass it to strip on libraries or executables.
 strip_g=false
@@ -112,6 +118,9 @@ strip_r=false
 
 # keep or remove arguments to eu-strip.
 keep_remove_args=
+
+# keep or remove symbols arguments
+keep_symbol_args=
 
 # with -m arg, add minimal debuginfo to binary.
 include_minidebug=false
@@ -225,6 +234,10 @@ while [ $# -gt 0 ]; do
     keep_remove_args="${keep_remove_args} --remove-section $2"
     shift
     ;;
+  --keep-symbol)
+    keep_symbol_args="${keep_symbol_args} --keep-symbol $2"
+    shift
+    ;;
   -j)
     n_jobs=$2
     shift
@@ -318,7 +331,32 @@ strip_to_debug()
   $strip_glibs && case "$(file -bi "$2")" in
     application/x-sharedlib*) g=-g ;;
   esac
-  eu-strip --remove-comment $r $g ${keep_remove_args} -f "$1" "$2" || exit
+
+  # SymCrypt-Specific: We need to keep certain symbols in the stripped binary, which eu-strip does not support.
+  # So instead we use strip, but that has different semantics.
+  #
+  # Original eu-strip command:
+  #     eu-strip --remove-comment $r $g ${keep_remove_args} ${keep_symbol_args} -f "$1" "$2" || exit
+  #
+  # Always remove the comment section
+  keep_remove_args="${keep_remove_args} --remove-section .comment"
+
+  # We don't set $r and $g in my testing. If we ever do set those, then this script
+  # will need to be modified to either find the equivalent in strip, or intentionally
+  # decide to not support these flags.
+  if [ -n "$r" ] || [ -n "$g" ]; then
+    echo >&2 "*** ERROR: strip_to_debug: r ('${r}') or g ('${r}') is set, but this script does not support it"
+    exit 2
+  fi
+
+  # strip has the -o flag instead of the -f flag, but the semantics are reversed
+  # For eu-strip, -f will extract the removed sections into the file given, leaving the original file alone.
+  # For strip, -o will write the stripped file to the given location, leaving original file alone.
+  # So we need to swap the arguments to strip.
+  mv "${2}" "${1}"
+
+  # The original cmake file for SymCrypt uses --strip-unneeded
+  strip --strip-unneeded ${keep_remove_args} ${keep_symbol_args} -o "$2" "$1" || exit
   chmod 444 "$1" || exit
 }
 
