Update dracut to v102 (#9501)
The dracut upstream has been abandoned, the latest is now found at dracut-ng. . The latest dracut tag, v059, was last updated two years ago meaning that if we want continued support we'll need to make the jump.

Update sources to the new upstream's latest tag, v102.

diff --git a/SPECS/dracut/0007-feat-dracut.sh-support-multiple-config-dirs.patch b/SPECS/dracut/0007-feat-dracut.sh-support-multiple-config-dirs.patch
--- a/SPECS/dracut/0007-feat-dracut.sh-support-multiple-config-dirs.patch
+++ b/SPECS/dracut/0007-feat-dracut.sh-support-multiple-config-dirs.patch
@@ -1,20 +1,19 @@
-From d1b46f8b53ceccabf33d4cc479a85778ba83abfb Mon Sep 17 00:00:00 2001
+From 1f59a485f2371eee0a691aa195e2a955a9b726d3 Mon Sep 17 00:00:00 2001
 From: Shreenidhi Shedi <sshedi@vmware.com>
 Date: Sat, 18 Feb 2023 18:11:51 +0530
-Subject: [PATCH 2/2] feat(dracut.sh): support multiple config dirs
+Subject: [PATCH] feat(dracut.sh): support multiple config dirs
 
 Configuration can come from many places, users should not be restricted
 to keep all configuration files in one directory.
 
 Signed-off-by: Shreenidhi Shedi <sshedi@vmware.com>
 ---
- dracut.sh          | 29 ++++++++++++++++++-----------
- man/dracut.8.asc   |  4 ++--
- mkinitrd-dracut.sh |  6 +++---
- 3 files changed, 23 insertions(+), 16 deletions(-)
+ dracut.sh        | 29 ++++++++++++++++++-----------
+ man/dracut.8.asc |  4 ++--
+ 2 files changed, 20 insertions(+), 13 deletions(-)
 
 diff --git a/dracut.sh b/dracut.sh
-index bbb3469..0787a92 100755
+index ff541e79..887b134d 100755
 --- a/dracut.sh
 +++ b/dracut.sh
 @@ -154,8 +154,9 @@ Creates initial ramdisk images for preloading modules
@@ -29,7 +28,7 @@ index bbb3469..0787a92 100755
    --tmpdir [DIR]        Temporary directory to be used instead of default
                           ${TMPDIR:-/var/tmp}.
    -r, --sysroot [DIR]   Specify sysroot directory to collect files from.
-@@ -668,7 +669,7 @@ while :; do
+@@ -674,7 +675,7 @@ while :; do
              shift
              ;;
          --confdir)
@@ -38,10 +37,10 @@ index bbb3469..0787a92 100755
              PARMS_TO_STORE+=" '$2'"
              shift
              ;;
-@@ -911,15 +912,20 @@ elif [[ ! -e $conffile ]]; then
+@@ -920,15 +921,20 @@ elif [[ ! -e $conffile ]]; then
      exit 1
  fi
-
+ 
 -if [[ -z $confdir ]]; then
 +if [ ${#confdirs_l[@]} -eq 0 ]; then
      if [[ $allowlocal ]]; then
@@ -52,7 +51,7 @@ index bbb3469..0787a92 100755
 +        confdirs_l=("$dracutsysrootdir/etc/dracut.conf.d")
      fi
 -elif [[ ! -d $confdir ]]; then
--    printf "%s\n" "dracut: Configuration directory '$confdir' not found." >&2
+-    printf "%s\n" "dracut[F]: Configuration directory '$confdir' not found." >&2
 -    exit 1
 +else
 +    # shellcheck disable=SC2068
@@ -63,12 +62,12 @@ index bbb3469..0787a92 100755
 +        fi
 +    done
  fi
-
+ 
  # source our config file
-@@ -929,8 +935,9 @@ if [[ -f $conffile ]]; then
+@@ -938,8 +944,9 @@ if [[ -f $conffile ]]; then
      . "$conffile"
  fi
-
+ 
 -# source our config dir
 -for f in $(dropindirs_sort ".conf" "$confdir" "$dracutbasedir/dracut.conf.d"); do
 +# source config files from all config dirs
@@ -78,13 +77,13 @@ index bbb3469..0787a92 100755
      # shellcheck disable=SC1090
      [[ -e $f ]] && . "$f"
 diff --git a/man/dracut.8.asc b/man/dracut.8.asc
-index 5c2b147..3eddb5a 100644
+index 25f601bd..9cd5d08a 100644
 --- a/man/dracut.8.asc
 +++ b/man/dracut.8.asc
-@@ -305,8 +305,8 @@ example:
+@@ -300,8 +300,8 @@ example:
  Default:
     _/etc/dracut.conf_
-
+ 
 -**--confdir** _<configuration directory>_::
 -    Specify configuration directory to use.
 +**--confdir** _<list of dracut configuration directories>_::
@@ -92,3 +91,6 @@ index 5c2b147..3eddb5a 100644
  +
  Default:
     _/etc/dracut.conf.d_
+-- 
+2.34.1
+
