Nicogbg/packer enable (#1426)
* debug

* 1st version of kickstart param

* pass unattended config file to runliveinstaller

* add .vscode in .gitignore

* address PR comments

* address PR comments

Co-authored-by: Nicolas Guibourge <nicolasg@microsoft.com>

diff --git a/toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller b/toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
--- a/toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
+++ b/toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
@@ -5,8 +5,30 @@
 export TERMINFO=/usr/lib/mariner/terminfo
 export TERM=mariner-installer
 
-# Mounting the ISO root for the installer.
 ISO_ROOT=/mnt/cdrom
+CONFIG_ROOT=$ISO_ROOT/config
+UNATTENDED_CONFIG_FILE=$CONFIG_ROOT/unattended_config.json
+
+# parse script parameters:
+#
+# -u -> unattended config file (optional)
+
+while getopts ":u:" OPTIONS; do
+  case "${OPTIONS}" in
+    u ) UNATTENDED_CONFIG_FILE=$OPTARG ;;
+
+    \? )
+        echo "Error - Invalid Option: -$OPTARG" 1>&2
+        exit 1
+        ;;
+    : )
+        echo "Error - Invalid Option: -$OPTARG requires an argument" 1>&2
+        exit 1
+        ;;
+  esac
+done
+
+# Mounting the ISO root for the installer.
 mkdir -p $ISO_ROOT
 LABEL=CDROM
 
@@ -28,10 +50,8 @@ else
     done
 fi
 
-CONFIG_ROOT=$ISO_ROOT/config
-
-# Restrict speakup use to attended installs
-if [[ ! -f "$CONFIG_ROOT/unattended_config.json" ]]; then
+if [[ ! -f "$UNATTENDED_CONFIG_FILE" ]]; then
+    # Restrict speakup use to attended installs
     # FIXME(thcrain-msft)
     # This is a loop of silence to keep the default audio device alive
     # This is a temporary workaround that is needed for VirtualBox,
@@ -54,7 +74,7 @@ cd /installer
 # Turn off echoing while the installer runs to stop sensitive data from rendering in the TTY session.
 stty -echo
 
-./liveinstaller --base-dir $CONFIG_ROOT --imager /installer/imager --input $CONFIG_ROOT/unattended_config.json --template-config $CONFIG_ROOT/attended_config.json \
+./liveinstaller --base-dir $CONFIG_ROOT --imager /installer/imager --input $UNATTENDED_CONFIG_FILE --template-config $CONFIG_ROOT/attended_config.json \
                 --build-dir $PWD --log-file=/installer/log.txt
 installerExitCode=$?
 
