Extracting raw toolchain download to a separate template.

diff --git a/.pipelines/templates/RawToolchainDownload.yml b/.pipelines/templates/RawToolchainDownload.yml
--- a/.pipelines/templates/RawToolchainDownload.yml
+++ b/.pipelines/templates/RawToolchainDownload.yml
@@ -10,25 +10,28 @@ parameters:
     type: string
 
 steps:
-  - bash: |  
+  - bash: |
+      set -e
+
       raw_toolchain_file_path="${{ parameters.coreRepoRoot }}/build/toolchain/toolchain_from_container.tar.gz"
 
       echo "-- Downloading cached raw toolchain."
-  
+
       mkdir -p "$(dirname "$raw_toolchain_file_path")"
-      wget --quiet --timeout=30 --continue "$(rawToolchainCacheURL)" -O "$raw_toolchain_file_path"
-      if [[ ! -f "$raw_toolchain_file_path" ]]; then
+      if ! wget --quiet --timeout=30 --continue "$RAW_TOOLCHAIN_URL" -O "$raw_toolchain_file_path"; then
           echo "-- ERROR: failed to download raw toolchain cache." >&2
-          return 1
+          exit 1
       fi
 
-      # Verifying toolchains SHA-256 hash.
+      # Verifying toolchain's SHA-256 hash.
       cache_sha256=$(sha256sum "$raw_toolchain_file_path" | cut -d' ' -f1)
-      if [[ "$cache_sha256" != "$(rawToolchainExpectedHash)" ]]; then
-          echo "-- ERROR: raw toolchain hash verification failed. Expected ($(rawToolchainExpectedHash)). Got ($cache_sha256)." >&2
-          return 1
+      if [[ "$cache_sha256" != "${{ parameters.rawToolchainExpectedHash }}" ]]; then
+          echo "-- ERROR: raw toolchain hash verification failed. Expected (${{ parameters.rawToolchainExpectedHash }}). Got ($cache_sha256)." >&2
+          exit 1
       fi
       echo "-- Raw toolchain hash OK."
 
       touch "$raw_toolchain_file_path"
+    env:
+      RAW_TOOLCHAIN_URL: ${{ parameters.rawToolchainCacheURL }}
     displayName: "Populate raw toolchain"
