Re-add missing for loop

diff --git a/.pipelines/templates/ToolchainBuild.yml b/.pipelines/templates/ToolchainBuild.yml
--- a/.pipelines/templates/ToolchainBuild.yml
+++ b/.pipelines/templates/ToolchainBuild.yml
@@ -66,13 +66,15 @@ steps:
       if [[ -f "$built_list" ]]; then
         built_specs=$(xargs < "$built_list")
         retest_list=()
-        if [ ! -f "${specs_dir}/${s}/${s}".spec ]; then
-            echo "ERROR: ${specs_dir}/${s}/${s}.spec does not exist"
-            exit 1
-        fi
-        if grep -q '^%check' "${specs_dir}/${s}/${s}".spec; then
-            test_list+=("${s}")
-        fi
+        for s in ${specs}; do
+          if [ ! -f "${specs_dir}/${s}/${s}".spec ]; then
+              echo "ERROR: '${specs_dir}/${s}/${s}.spec' does not exist"
+              exit 1
+          fi
+          if grep -q '^%check' "${specs_dir}/${s}/${s}.spec"; then
+              test_list+=("${s}")
+          fi
+        done
       fi
       # Default will be "", which is fine.
       echo "##vso[task.setvariable variable=packageTestList;isOutput=true]${test_list[*]}"
