Disabling spec render check.

diff --git a/.github/workflows/ado/templates/sources-upload-stages.yml b/.github/workflows/ado/templates/sources-upload-stages.yml
--- a/.github/workflows/ado/templates/sources-upload-stages.yml
+++ b/.github/workflows/ado/templates/sources-upload-stages.yml
@@ -94,7 +94,10 @@ stages:
                 echo "##[group]Git diff"
                 git --no-pager diff -- "$specs_dir"
                 echo "##[endgroup]"
-                exit 1
+                echo "##[warning]Specs are not up to date. Ignoring until main branch is updated and stable."
+                # TODO: Re-enabled failing once specs in the main branch are updated and stable.
+                #       ADO task: 
+                # exit 1
               fi
             displayName: "Verify rendered specs are up to date"
 
