debug

diff --git a/.pipelines/prchecks/PackageBuildPRCheck.yml b/.pipelines/prchecks/PackageBuildPRCheck.yml
--- a/.pipelines/prchecks/PackageBuildPRCheck.yml
+++ b/.pipelines/prchecks/PackageBuildPRCheck.yml
@@ -90,6 +90,11 @@ extends:
                   ob_outputDirectory: $(Build.ArtifactStagingDirectory)
                   testListFromToolchain: $[ stageDependencies.Toolchain_${{ configuration.name }}.CalculatePackageRetestList.outputs['packageTestList'] ]
                 steps:
+                  - script: |
+                      if [[ -z "${{ variables.testListFromToolchain }}" ]]; then
+                        echo "ERROR: testListFromToolchain is empty!" >&2
+                        exit 1
+                      fi
                   - template: .pipelines/templates/PackageBuild.yml@self
                     parameters:
                       customToolchainArtifactName: $(toolchainArtifactNameBase)_${{ configuration.name }}
