debug

diff --git a/.github/workflows/check-package-gate.yml b/.github/workflows/check-package-gate.yml
--- a/.github/workflows/check-package-gate.yml
+++ b/.github/workflows/check-package-gate.yml
@@ -47,19 +47,30 @@ jobs:
           echo "No spec files to validate. Exiting."
           exit 0
         fi
-        
+
+
         for spec in ${{ env.updated-specs }}
           do
             echo "Checking '$spec'."
             name=$(grep -E "^Name:\s*(.*)" "$spec" | awk '{print $2}')
             version=$(grep -E "^Version:\s*(.*)" "$spec" | awk '{print $2}')
+
+            if [[ "$name" == "fdk-aac-free" || "$name" == "opus" ]]; then
+              previous_version=$(git show ${{ env.base_sha }}:"$spec" | grep -E "^Version:\s*(.*)" | awk '{print $2}')
+              if [[ "$version" != "$previous_version" ]]; then
+                1>&2 echo "**** ERROR ****"
+                1>&2 echo "Spec '$spec' change is not allowed in Azure Linux."
+                1>&2 echo "**** ERROR ****"
+                error_found=1
+              fi
+            fi
+
+
             if [[ "$name" == "redis" && "$version" >= "7.4" ]] || \
                 [[ "$name" == "packer" && "$version" >= "1.10.0" ]] || \
-                [[ "$name" == "terraform" && "$version" >= "1.6.0" ]] || \
-                [[ "$name" == "fdk-aac-free" ]] || \
-                [[ "$name" == "opus" ]]; then
+                [[ "$name" == "terraform" && "$version" >= "1.6.0" ]]; then
             1>&2 echo "**** ERROR ****"
-            1>&2 echo "Spec '$spec' does not meet the required version criteria."
+            1>&2 echo "Spec '$spec' change is not allowed in Azure Linux."
             1>&2 echo "**** ERROR ****"
             error_found=1
             fi
