Check clean-up .

diff --git a/.github/workflows/check-clean-stage.yml b/.github/workflows/check-clean-stage.yml
--- a/.github/workflows/check-clean-stage.yml
+++ b/.github/workflows/check-clean-stage.yml
@@ -34,10 +34,12 @@ jobs:
 
           for spec in $changed_specs
           do
-            echo "Checking '%$spec'."
+            echo "Checking '$spec'."
             if grep -q "^\s*%clean" "$spec"
             then
-              1>&2 echo "ERROR: spec '$spec' contains a %clean stage, which should be unnecessary for CBL-Mariner. Please remove it or add an exception for this spec file."
+              1>&2 echo "**** ERROR ****"
+              1>&2 echo "Spec '$spec' contains a %clean stage, which should be unnecessary for CBL-Mariner. Please remove it or add an exception for this spec file."
+              1>&2 echo "**** ERROR ****"
               error_found=1
             fi
           done
