Make lint-specs.yml more resilient to failure

diff --git a/.github/workflows/lint-specs.yml b/.github/workflows/lint-specs.yml
--- a/.github/workflows/lint-specs.yml
+++ b/.github/workflows/lint-specs.yml
@@ -80,13 +80,18 @@ jobs:
         run: |
           mkdir -p linted_specs
           spec-cleaner -o linted_specs ${{ env.updated-specs }}
-          [ -n "$(ls -A linted_specs)" ] \
-          && echo "Specs are not correctly formatted." \
-          && echo "Linting output is available in the linted_specs artifact." \
-          && echo "Please properly format your specs according to that output before merging." \
-          && echo "A diff of the changes required is printed below:" \
-          && spec-cleaner -d --diff-prog="git --no-pager diff" ${{ env.updated-specs }} \
-          && exit 1
+          for FILE in $(find linted_specs -name "*.spec")
+          do
+            if [ -s $FILE ]
+            then
+              echo "Specs are not correctly formatted."
+              echo "Linting output is available in the linted_specs artifact."
+              echo "Please properly format your specs according to that output before merging."
+              echo "A diff of the changes required is printed below:"
+              spec-cleaner -d --diff-prog="git --no-pager diff" ${{ env.updated-specs }}
+              exit 1
+            fi
+          done
 
       - uses: actions/upload-artifact@v2
         if: ${{ always() }}
